name: Cron Test Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # 매 1분마다 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  cron-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Python test
        run: |
          python -V
          python test.py
